---
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.2.0"
  - "2.3.0"
  - "2.4.0"
  - "2.5.0"
  - "2.6.0"
  - ruby-head

# matrix:
#   allow_failures:
#     - rvm: ruby-head  # Stdlib are creating issues, those will be deleted next version...

before_install:
  - git submodule update --init --recursive
